---
title: Вики компании ПАК-ВМ
baseURL: "/"
params:
  description: Вики для сотрудников ПАК-ВМ
  palette: blue
  palettes:
    blue:
      type: palette
      template: palette
      sass:
        accent1: "#00c6ff"
        accent2: "#0072ff"
    green:
      type: palette
      template: palette
      sass:
        accent1: "#12db5d"
        accent2: "#11998e"
    navy:
      type: palette
      template: palette
      sass:
        accent1: "#004e92"
        accent2: "#000428"
    violet:
      type: palette
      template: palette
      sass:
        accent1: "#8e2de2"
        accent2: "#4a00e0"
  header:
    type: header
    template: header
    title: Вики компании ПАК-ВМ
    logo_img: "/images/packvm_1x.jpg"
    has_nav: true
    nav_links:
    - type: action_menu
      template: action_menu
      label: Главная
      url: "/"
      style: link
      has_subnav: false
    - type: action_menu
      template: action_menu
      label: Документация
      url: "/docs"
      style: link
      has_subnav: false
    - type: action_menu
      template: action_menu
      label: Новости
      url: "/blog"
      style: link
      has_subnav: false
    - type: action_menu
      template: action_menu
      label: Правила внутреннего этикета
      url: "/style-guide"
      style: link
      has_subnav: false
    url: https://packvm-wiki.netlify.app/
  footer:
    type: footer
    template: footer
    content: "&copy; Stackbit-Libris. All rights reserved."
    links:
    - type: action
      template: action
      label: Made with Stackbit
      url: https://www.stackbit.com
      style: link
      new_window: true
    has_social: false
    social_links:
    - type: action
      template: action
      label: Twitter
      url: https://twitter.com/
      style: icon
      icon_class: fa-twitter
      new_window: true
    - type: action
      template: action
      label: LinkedIn
      url: https://www.linkedin.com/
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - type: action
      template: action
      label: GitHub
      url: https://github.com/
      style: icon
      icon_class: fa-github
      new_window: true
taxonomies:
  stub: stub
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
